_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.18.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
batch_size:
    value: 32
dropout:
    value: 0.1
embed_size:
    value: 64
forward_expansion:
    value: 4
heads:
    value: 4
learning_rate:
    value: 0.0003
max_length:
    value: 30
num_epochs:
    value: 1
num_layers:
    value: 3
num_samples:
    value: 1000
